swagger: '2.0'
info:
  description: Data Hub Company API V2
  version: 1.0.0
  title: Company API
  contact:
    email: jim.smith@digital.trade.gov.uk
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

basePath: /v2

tags:
- name: public
  description: API open to Data Hub client
- name: company
  description: Belongs to company operations in Data Hub
schemes:
- https
- http
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: password
    tokenUrl: '/token/'
    scopes:
      user: User scope

security:
  - OauthSecurity:
    - user

paths:
  /company/{companyId}:
    get:
      tags:
      - company
      summary: Returns a company from the Data Hub repository
      operationId: getcompany
      description: |
        Passing in a company UUID returns a Data Hub company object
      produces:
      - application/vnd.api+json
      parameters:
      - in: path
        name: companyId
        description: UUID for a Data Hub company
        default: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: JSON API formatted company object
          schema:
            $ref: '#/definitions/Company'
        400:
          description: bad input parameter
        404:
          description: company does not exist
    put:
      tags:
      - company
      summary: updates a company, creating a new one if not found
      operationId: updateCompany
      description: Updates an existing company
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - in: path
        name: companyId
        description: UUID for a Data Hub company
        default: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
        type: string
        required: true
      - in: body
        name: company
        description: Company data to update
        required: true
        schema:
          $ref: '#/definitions/Company'
      responses:
        200:
          description: item updated
        201:
          description: item created
        400:
          description: invalid input, object invalid
  /company:
    post:
      tags:
      - company
      summary: adds a Data Hub company
      operationId: addCompany
      description: Adds a Data Hub company from a Companies House company
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - in: body
        name: company
        description: Company to add
        required: true
        schema:
          $ref: '#/definitions/Company'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: company already exists
  /ch_company/{company_number}:
    get:
      tags:
      - company
      summary: Returns a Companies House company from the Data Hub repository
      operationId: getchcompany
      description: |
        Passing in a Companies House company number returns a Data Hub Companies House company object
      produces:
      - application/vnd.api+json
      parameters:
      - in: path
        name: company_number
        description: Companies House number
        default: '123456789'
        required: true
        type: string
      responses:
        200:
          description: JSON API formatted company object
          schema:
            $ref: '#/definitions/CompaniesHouseCompany'
        400:
          description: bad input parameter
        404:
          description: company does not exist
definitions:
  Company:
    type: object
    description: A representation of the Data Hub company object
    required:
    - data
    - companyId
    properties:
      id:
        type: string
        example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
      data:
        title: Company Top Level
        type: object
        required:
        - type
        - attributes
        - relationships
        - links
        properties:
          type:
            type: string
            example: 'Company'
          id:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
          attributes:
            title: Company
            type: object
            required:
            - name
            - registered_address_1
            - registered_address_town
            properties:
              name:
                type: string
                example: 'EXAMPLE Ltd'
              trading_name:
                type: string
                example: 'Example Trading'
              uk_based:
                type: boolean
              registered_address_1:
                type: string
                example: '123 HIGH STREET'
              registered_address_2:
                type: string
                example: 'AREA'
              registered_address_3:
                type: string
                example: 'SUBTOWN'
              registered_address_4:
                type: string
                example: 'SUBREGION'
              registered_address_town:
                type: string
                example: 'ANYTOWN'
              registered_address_county:
                type: string
                example: 'ANYSHIRE'
              registered_address_postcode:
                type: string
                example: 'AB1 2CD'
              created_on:
                type: string
                format: date-time
                example: 2014-07-23T10:36:04
              modified_on:
                type: string
                format: date-time
                example: 2014-07-23T10:36:04
              archived:
                type: boolean
              archived_on:
                type: string
                format: date-time
                example: 2014-07-23T10:36:04
              archived_reason:
                type: string
                example: 'Company dissolved'
              archived_by:
                type: string
                example: 'A N Advisor'
              lead:
                type: boolean
              description:
                type: string
                example: 'MANUFACTURER OF WIDGETS AND DOODADS'
              website:
                type: string
                example: 'http://www.example.com'
              trading_address_1:
                type: string
                example: '123 HIGH STREET'
              trading_address_2:
                type: string
                example: 'AREA'
              trading_address_3:
                type: string
                example: 'SUBTOWN'
              trading_address_4:
                type: string
                example: 'SUBREGION'
              trading_address_town:
                type: string
                example: 'ANYTOWN'
              trading_address_county:
                type: string
                example: 'ANYSHIRE'
              trading_address_postcode:
                type: string
                example: 'AB1 2CD'
              headquarter_type:
                type: string
                example: 'UK Headquarters'
          relationships:
            $ref: '#/definitions/CompanyRelationships'
          links:
            type: object
            properties:
              self:
                type: string
                example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851'
  CompanyRelationships:
    type: object
    properties:
      account_manager:
        $ref: '#/definitions/Advisor'
      business_type:
        $ref: '#/definitions/BusinessType'
      children:
        $ref: '#/definitions/CompanyKeyArray'
      classification:
        $ref: '#/definitions/Classification'
      companies_house_data:
        $ref: '#/definitions/CompaniesHouseData'
      contacts:
        $ref: '#/definitions/ContactArray'
      employee_range:
        $ref: '#/definitions/EmployeeRange'
      export_to_countries:
        $ref: '#/definitions/CountryArray'
      future_interest_countries:
        $ref: '#/definitions/CountryArray'
      interactions:
        $ref: '#/definitions/InteractionArray'
      one_list_owner:
        $ref: '#/definitions/Advisor'
      parents:
        $ref: '#/definitions/CompanyKeyArray'
      registered_address_country:
          $ref: '#/definitions/Country'
      sector:
        $ref: '#/definitions/Sector'
      trading_address_country:
          $ref: '#/definitions/Country'
      turnover_range:
        $ref: '#/definitions/TurnoverRange'
      uk_region:
        $ref: '#/definitions/UKRegion'
  Advisor:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
          type:
            type: string
            example: 'Advisor'
  BusinessType:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
          type:
            type: string
            example: 'BusinessType'
  Classification:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
          type:
            type: string
            example: 'OneListClassifaction'
  CompaniesHouseData:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: string
            example: 'SCO-123456'
          type:
            type: string
            example: 'CompaniesHouse'
  CompanyKeyArray:
    type: object
    required:
    - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/CompanyRaw'
      meta:
        type: object
        properties:
          count:
            type: integer
            example: 30
      links:
        type: object
        properties:
          self:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/children?page[offset]=0&page[limit]=10'
          next:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/parents?page[offset]=10&page[limit]=10'
          prev:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/children?page[offset]=0&page[limit]=10'
          last:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/parents?page[offset]=120&page[limit]=10'
  CompanyRaw:
    type: object
    required:
      - id
      - type
    properties:
      id:
        type: string
        format: uuid
        example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
      type:
        type: string
        example: 'Company'
  ContactArray:
    type: object
    required:
    - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ContactRaw'
  ContactRaw:
    type: object
    required:
      - id
      - type
    properties:
      id:
        type: string
        format: uuid
        example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
      type:
        type: string
        example: 'Contact'
  Country:
    type: object
    required:
    - data
    properties:
      data:
        $ref: '#/definitions/CountryRaw'
  CountryArray:
    type: object
    required:
    - data
    properties:
      meta:
        type: object
        properties:
          count:
            type: integer
            example: 30
      links:
        type: object
        properties:
          self:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/exportToCountries?page[offset]=0&page[limit]=10'
          next:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/futureInterestCountries?page[offset]=10&page[limit]=10'
          prev:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/exportToCountries?page[offset]=0&page[limit]=10'
          last:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/futureInterestCountries?page[offset]=120&page[limit]=10'
      data:
        type: array
        items:
          $ref: '#/definitions/CountryRaw'
  CountryRaw:
    type: object
    required:
      - id
      - type
    properties:
      id:
        type: string
        format: uuid
        example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
      type:
        type: string
        example: 'Country'
  Interaction:
    type: object
    required:
      - id
      - type
    properties:
      id:
        type: string
        format: uuid
        example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
      type:
        type: string
        example: 'Interaction'
  InteractionArray:
    type: object
    required:
    - data
    properties:
      meta:
        type: object
        properties:
          count:
            type: integer
            example: 30
      links:
        type: object
        properties:
          self:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/interactions?page[offset]=0&page[limit]=10'
          next:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/interactions?page[offset]=10&page[limit]=10'
          prev:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/interactions?page[offset]=0&page[limit]=10'
          last:
            type: string
            example: 'http://HOST/v2/company/d290f1ee-6c54-4b01-90e6-d701748f0851/interactions?page[offset]=120&page[limit]=10'
      data:
        type: array
        items:
          $ref: '#/definitions/Interaction'
  EmployeeRange:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
          type:
            type: string
            example: 'EmployeeRange'
  Sector:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
          type:
            type: string
            example: 'Sector'
  TurnoverRange:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: uuid
          type:
            type: string
            example: 'TurnoverRange'
  UKRegion:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - id
          - type
        properties:
          id:
            type: string
            format: uuid
            example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
          type:
            type: string
            example: 'UKRegion'
  CompaniesHouseCompany:
    type: object
    description: A Companies House company object
    required:
    - data
    properties:
      data:
        title: Company Top Level
        type: object
        required:
        - type
        - attributes
        - links
        - id # company number
        properties:
          type:
            type: string
            example: 'CompaniesHouseCompany'
          id:
            type: string
            example: 'SCO-123456'
          attributes:
            title: CompaniesHouseCompany
            type: object
            required:
            - name
            - registered_address_1
            - registered_address_town
            - company_number
            properties:
              name:
                type: string
              registered_address_1:
                type: string
                example: '123 HIGH STREET'
              registered_address_2:
                type: string
                example: 'AREA'
              registered_address_town:
                type: string
                example: 'ANYTOWN'
              registered_address_county:
                type: string
                example: 'ANYSHIRE'
              registered_address_postcode:
                type: string
                example: 'AB1 2CD'
              company_number:
                type: string
                example: 'SCO-123456'
              company_category:
                type: string
                example: 'Private Limited Company'
              company_status:
                type: string
                example: 'Active - Proposal to Strike off'
              sic_code_1:
                type: string
                example: '20600 - Manufacture of man-made fibres'
              sic_code_2:
                type: string
                example: '52211 - Operation of rail freight terminals'
              sic_code_3:
                type: string
                example: '71111 - Architectural activities'
              sic_code_4:
                type: string
                example: '96030 - Funeral and related activities'
              uri:
                type: string
                example: 'http://www.example.com'
              incorporation_date:
                type: string
                format: date-time
                example: 2014-07-23T10:36:04
          links:
            type: object
            properties:
              self:
                type: string
                example: 'http://HOST/v2/ch_company/d290f1ee-6c54-4b01-90e6-d701748f0851'