# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.advisor import Advisor


class TestAdvisor(unittest.TestCase):
    """ Advisor unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdvisor(self):
        """
        Test Advisor
        """
        model = swagger_client.models.advisor.Advisor()


if __name__ == '__main__':
    unittest.main()
