# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.investment_team import InvestmentTeam


class TestInvestmentTeam(unittest.TestCase):
    """ InvestmentTeam unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvestmentTeam(self):
        """
        Test InvestmentTeam
        """
        model = swagger_client.models.investment_team.InvestmentTeam()


if __name__ == '__main__':
    unittest.main()
