# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.company_api import CompanyApi


class TestCompanyApi(unittest.TestCase):
    """ CompanyApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.company_api.CompanyApi()

    def tearDown(self):
        pass

    def test_add_company(self):
        """
        Test case for add_company

        adds a Data Hub company
        """
        pass

    def test_getchcompany(self):
        """
        Test case for getchcompany

        Returns a Companies House company from the Data Hub repository
        """
        pass

    def test_getcompany(self):
        """
        Test case for getcompany

        Returns a company from the Data Hub repository
        """
        pass

    def test_update_company(self):
        """
        Test case for update_company

        updates a company, creating a new one if not found
        """
        pass


if __name__ == '__main__':
    unittest.main()
