# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.metadata_api import MetadataApi


class TestMetadataApi(unittest.TestCase):
    """ MetadataApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.metadata_api.MetadataApi()

    def tearDown(self):
        pass

    def test_metadata_business_actibvity(self):
        """
        Test case for metadata_business_actibvity

        retrieves Business Activity metadata array
        """
        pass


if __name__ == '__main__':
    unittest.main()
