# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.company import Company


class TestCompany(unittest.TestCase):
    """ Company unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompany(self):
        """
        Test Company
        """
        model = swagger_client.models.company.Company()


if __name__ == '__main__':
    unittest.main()
