# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.non_fdi_type import NonFDIType


class TestNonFDIType(unittest.TestCase):
    """ NonFDIType unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFDIType(self):
        """
        Test NonFDIType
        """
        model = swagger_client.models.non_fdi_type.NonFDIType()


if __name__ == '__main__':
    unittest.main()
