# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.documents_inner import DocumentsInner


class TestDocumentsInner(unittest.TestCase):
    """ DocumentsInner unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentsInner(self):
        """
        Test DocumentsInner
        """
        model = swagger_client.models.documents_inner.DocumentsInner()


if __name__ == '__main__':
    unittest.main()
