# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.investment_filtered_search import InvestmentFilteredSearch


class TestInvestmentFilteredSearch(unittest.TestCase):
    """ InvestmentFilteredSearch unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvestmentFilteredSearch(self):
        """
        Test InvestmentFilteredSearch
        """
        model = swagger_client.models.investment_filtered_search.InvestmentFilteredSearch()


if __name__ == '__main__':
    unittest.main()
