# coding: utf-8

"""
    Data Hub API

    Data Hub API

    OpenAPI spec version: 1.0.0
    Contact: jim.smith@digital.trade.gov.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.investment_team_member_array import InvestmentTeamMemberArray


class TestInvestmentTeamMemberArray(unittest.TestCase):
    """ InvestmentTeamMemberArray unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvestmentTeamMemberArray(self):
        """
        Test InvestmentTeamMemberArray
        """
        model = swagger_client.models.investment_team_member_array.InvestmentTeamMemberArray()


if __name__ == '__main__':
    unittest.main()
